### PR TITLE
Added dynamic $ago replacement variable

### PR DESCRIPTION
**Pull request by VirtualMarten**
Added this for myself, thought others might want to use it.

(_Spent the afternoon figuring out forks, pull requests and the like._)

### CODE REVIEW

**Comment by Strencher** [comment]
Good work, but unfortunately, you'd have to apply those changes inside the `development` branch. Don't worry about building, my workflow does that for you.

**Comment by VirtualMarten** [comment]
Good to know, should I close this Pull Request?

**Comment by Strencher** [comment]
Ideally yeah. Just make a new one, it's fine.

**Comment by VirtualMarten** [comment]
> Ideally yeah. Just make a new one, it's fine.

I was able to just switch the target branch to development, looks like that worked alright. (I hope.)

**Comment by Strencher** [comment]
No, it didn't, you have tons of conflicts now. Making a new one is fairly easier.

**Pull request closed without merging**
