### PR TITLE
Fix SuppressReplyMentions

### PR DESCRIPTION
**Pull request by HypedDomi**
Since i cant update PRs and Alli is inactive, i fixed her PR

### CODE REVIEW

**Review by Strencher — APPROVED** [review]

**Comment by Riolku** [comment]
I'm glad you fixed the plugin, but you also removed the changes added by #166 and #203. What happened here?

**Comment by HypedDomi** [comment]
The only thing that changed in this PR was this:
image

**Comment by HypedDomi** [comment]
Ah, I accidentally removed it when I merged it manual. I'll add it back

**Comment by Riolku** [comment]
Make sure to fix the changelog and version number too

**Comment by HypedDomi** [comment]
Done: [d570ac9](https://github.com/Strencher/BetterDiscordStuff/commit/d570ac9e8cf3127a62dbbb112155547fbe6cf48d)

**Comment by Riolku** [comment]
Thanks!

Curious: was the change altering appearance of replies? I thought it was adding a setting for forcing mentions

**Comment by HypedDomi** [comment]
Yeah it was adding a option to force the Mentions

**Pull request merged**
