### PR TITLE
Fix Manual Pings

### PR DESCRIPTION
**Pull request by Riolku**
Fixed Manual pings.

Also, added a setting to allow DMs to ping regardless of replying. I feel like this is the expected behaviour, but a setting is probably still the right way to go.

### CODE REVIEW

**Comment by HypedDomi** [comment]
I don't see what that's supposed to do. You still have the 1 regardless of whether you activate or deactivate the ping. And then you can also use the settings that currently already exist

**Comment by Riolku** [comment]
With the default (suppress replies), manual ping off, and "disable ping when replying", the following behaviour occurs in DMs:

- Replies don't ping.
- When replying, you don't ping the other person.

**Comment by HypedDomi** [comment]
Yes, but the person still gets the notification, so it doesn't matter if you ping/get pinged

**Comment by Riolku** [comment]
How sure are you about that? I did test this...

**Comment by HypedDomi** [comment]
I tested it too. You still get the Notification regardless of whether it is with or without a ping
img

**Comment by Riolku** [comment]
What about sound & desktop notification?

**Comment by HypedDomi** [comment]
> What about sound & desktop notification?

You get that too. Depends on the Status and Chat Settings from the guy you dmed

**Pull request merged**
